### PR TITLE
Eeprom methods

### PR DESCRIPTION
**Pull request by noopkat**
Hello!

I'm restoring these methods as they'd be really useful for me to have. I think it's ok to just support paged for now if that's cool. The diff is really confusing looking, sorry :cry: 

Let me know! And thanks for writing this library :+1: 

Suz

### CODE REVIEW

**Comment by jacobrosenthal** [comment]
Looks good to me. Dont think I have my device on me. I presume everything works for you and is ready for merge?

**Comment by noopkat** [comment]
It was working, but let me double check one more time to make sure I wasn't imagining it as that has happened before 😅

**Comment by jacobrosenthal** [comment]
Thanks! Apparently i published out of a branch last so I'll have to merge stuff and might ask you to check that again then if you're available....

**Comment by noopkat** [comment]
np at all!

**Comment by jacobrosenthal** [comment]
I found my stick and existing code all still works so merging assuming this is working for you. Merged into master and Released as 0.0.3

**Pull request closed without merging**
